name: k2_staff
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  app_settings: ^4.1.1
  carousel_slider: ^4.0.0
  collection: ^1.15.0
  #cupertino_icons: ^1.0.3
  easy_debounce: ^2.0.1
  equatable: ^2.0.3
  flutter_bloc: ^7.3.3
  flutter_beacon: 
    git:
      url: git@ssh.dev.azure.com:v3/kangarootime/K2.1/flutter_beacon
  flutter_localizations:
    sdk: flutter
  flutter_phoenix: ^1.0.0
  flutter_settings_ui: ^2.0.1
  get_it: ^7.2.0
  #hydrated_bloc: ^7.1.0
  intl: ^0.17.0
  intl_utils: ^2.4.1
  jiffy: ^4.1.0
  #json_annotation: ^4.3.0
  k2_flutter_api:
    # path: ../k2-flutter-api/
    git:
      url: git@ssh.dev.azure.com:v3/kangarootime/K2.1/k2-flutter-api

      ref: dev  
  k2_flutter_core:
 #   path: /k/k2-flutter-core/
    git:
      url: git@ssh.dev.azure.com:v3/kangarootime/K2.1/k2-flutter-core
      ref: develop    
#  launchdarkly_flutter: ^1.1.0
  logging: ^1.0.2
#  pedantic: ^1.9.0
 # pin_code_fields: ^7.1.0
  #pinput: ^1.2.0
  measured_size: ^1.0.0
  ntp: ^2.0.0
  qlevar_router: ^1.5.9
  # qr_code_scanner: ^0.7.0
  permission_handler: ^9.2.0
  pull_to_refresh: ^2.0.0
  qr_code_scanner: ^1.0.0
  responsive_builder: ^0.4.1
  shared_preferences: ^2.0.8
  table_calendar: ^3.0.3
  timezone: ^0.8.0
  # uni_links: ^0.5.1
  #usage: ^4.0.2
  #timezone: ^0.7.0-nullsafety.0
  websafe_svg: ^2.1.1
  webview_flutter: ^3.0.0

# dependency_overrides:
#     qr_code_scanner:
#         git:
#             url: https://github.com/X-SLAYER/qr_code_scanner.git
#             ref: flutter-beta

dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  dependency_validator: ^3.0.0
  flutter_launcher_icons: ^0.9.2
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProximaSoft
      fonts:
        - asset: assets/fonts/proximasoft/mark_simonson_proxima_soft.otf
        - asset: assets/fonts/proximasoft/mark_simonson_proxima_soft_black.otf
        - asset: assets/fonts/proximasoft/mark_simonson_proxima_soft_black_it.otf
        - asset: assets/fonts/proximasoft/mark_simonson_proxima_soft_bold.otf
          weight: 700
        - asset: assets/fonts/proximasoft/mark_simonson_proxima_soft_extrabold.otf
          weight: 900
        - asset: assets/fonts/proximasoft/mark_simonson_proxima_soft_light.otf
          weight: 300
        - asset: assets/fonts/proximasoft/mark_simonson_proxima_soft_medium.otf
          weight: 500
        - asset: assets/fonts/proximasoft/mark_simonson_proxima_soft_semibold.otf
          weight: 700
        - asset: assets/fonts/proximasoft/mark_simonson_proxima_soft_thin.otf
          weight: 300

flutter_intl:
  main_locale: en_US
  enabled: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true